name: kbicog
favicon: null
layout_spectrum: 0.0566060992423445
typography_spectrum: 0.017844033893197775
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.03058537980541587
  lightness: 0.5589147487189621
  saturation: 0.5018528546206653
  rhythmicContrast: 0.4056065424811095
purpose: []
